version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    restart: on-failure
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
    postgres_data:
